-- MySQL Script generated by MySQL Workbench
-- Mon 16 May 2016 19:05:14 EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ideaspacesdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ideaspacesdb` ;

-- -----------------------------------------------------
-- Schema ideaspacesdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ideaspacesdb` DEFAULT CHARACTER SET utf8 ;
USE `ideaspacesdb` ;

-- -----------------------------------------------------
-- Table `ideaspacesdb`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ideaspacesdb`.`USER` ;

CREATE TABLE IF NOT EXISTS `ideaspacesdb`.`USER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `EMAIL` VARCHAR(45) NOT NULL,
  `FIRST_NAME` VARCHAR(45) NOT NULL,
  `LAST_NAME` VARCHAR(45) NOT NULL,
  `PASSWORD_HASH` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ideaspacesdb`.`IDEA_SPACE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ideaspacesdb`.`IDEA_SPACE` ;

CREATE TABLE IF NOT EXISTS `ideaspacesdb`.`IDEA_SPACE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  `ADMIN` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_IDEA_SPACE_USER_ID`
    FOREIGN KEY (`ADMIN`)
    REFERENCES `ideaspacesdb`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_IDEA_SPACE_USER_ID_idx` ON `ideaspacesdb`.`IDEA_SPACE` (`ADMIN` ASC);


-- -----------------------------------------------------
-- Table `ideaspacesdb`.`MEMBER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ideaspacesdb`.`MEMBER` ;

CREATE TABLE IF NOT EXISTS `ideaspacesdb`.`MEMBER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USER_ID` INT NOT NULL,
  `IDEA_SPACE_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_MEMBER_USER_ID`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `ideaspacesdb`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MEMBER_IDEA_SPACE_ID`
    FOREIGN KEY (`IDEA_SPACE_ID`)
    REFERENCES `ideaspacesdb`.`IDEA_SPACE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_MEMBER_IDEA_SPACE_ID_idx` ON `ideaspacesdb`.`MEMBER` (`IDEA_SPACE_ID` ASC);


-- -----------------------------------------------------
-- Table `ideaspacesdb`.`IDEA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ideaspacesdb`.`IDEA` ;

CREATE TABLE IF NOT EXISTS `ideaspacesdb`.`IDEA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `MEMBER_ID` INT NOT NULL,
  `IDEA_SPACE_ID` INT NOT NULL,
  `TTILE` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_IDEA_MEMBER_ID`
    FOREIGN KEY (`MEMBER_ID`)
    REFERENCES `ideaspacesdb`.`MEMBER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IDEA_IDEA_SPACE_ID`
    FOREIGN KEY (`IDEA_SPACE_ID`)
    REFERENCES `ideaspacesdb`.`IDEA_SPACE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_IDEA_IDEA_SPACE_ID_idx` ON `ideaspacesdb`.`IDEA` (`IDEA_SPACE_ID` ASC);

CREATE INDEX `fk_IDEA_MEMBER_ID_idx` ON `ideaspacesdb`.`IDEA` (`MEMBER_ID` ASC);


-- -----------------------------------------------------
-- Table `ideaspacesdb`.`VOTING`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ideaspacesdb`.`VOTING` ;

CREATE TABLE IF NOT EXISTS `ideaspacesdb`.`VOTING` (
  `MEMBER_ID` INT NOT NULL,
  `IDEA_ID` INT NOT NULL,
  `RATING_NUMBER` INT NOT NULL,
  PRIMARY KEY (`MEMBER_ID`, `IDEA_ID`),
  CONSTRAINT `fk_VOTING_MEMBER_ID`
    FOREIGN KEY (`MEMBER_ID`)
    REFERENCES `ideaspacesdb`.`MEMBER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VOTING_IDEA_ID`
    FOREIGN KEY (`IDEA_ID`)
    REFERENCES `ideaspacesdb`.`IDEA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_VOTING_IDEA_ID_idx` ON `ideaspacesdb`.`VOTING` (`IDEA_ID` ASC);


-- -----------------------------------------------------
-- Table `ideaspacesdb`.`COMMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ideaspacesdb`.`COMMENT` ;

CREATE TABLE IF NOT EXISTS `ideaspacesdb`.`COMMENT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `IDEA_ID` INT NOT NULL,
  `MEMBER_ID` INT NOT NULL,
  `CONTENT` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_COMMENT_MEMBER_ID`
    FOREIGN KEY ()
    REFERENCES `ideaspacesdb`.`MEMBER` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMMENT_IDEA_ID`
    FOREIGN KEY (`IDEA_ID`)
    REFERENCES `ideaspacesdb`.`IDEA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_COMMENT_IDEA_ID_idx` ON `ideaspacesdb`.`COMMENT` (`IDEA_ID` ASC);


-- -----------------------------------------------------
-- Table `ideaspacesdb`.`FAVORITES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ideaspacesdb`.`FAVORITES` ;

CREATE TABLE IF NOT EXISTS `ideaspacesdb`.`FAVORITES` (
  `MEMBER_ID` INT NOT NULL,
  `IDEA_ID` INT NOT NULL,
  PRIMARY KEY (`MEMBER_ID`, `IDEA_ID`),
  CONSTRAINT `fk_FAVORITES_MEMBER_ID`
    FOREIGN KEY (`MEMBER_ID`)
    REFERENCES `ideaspacesdb`.`MEMBER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FAVORITES_IDEA_ID`
    FOREIGN KEY (`IDEA_ID`)
    REFERENCES `ideaspacesdb`.`IDEA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_FAVORITES_IDEA_ID_idx` ON `ideaspacesdb`.`FAVORITES` (`IDEA_ID` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
