source 'https://rubygems.org'

gem 'bundler'
gem 'rake'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'dm-core'
gem 'dm-types'
gem 'dm-serializer'
gem 'dm-migrations'
gem 'sqlite3'
gem 'dm-sqlite-adapter'

group :development, :test do
  gem 'shotgun' # Auto-reload sinatra app on change.
  gem 'better_errors' # Show an awesome console in the browser on error.
end

group :test do
  gem 'rspec'
  gem 'rack-test'
end
